name: psychology and tech
favicon: null
layout_spectrum: 0.7988402845803648
typography_spectrum: 0.8986094500869513
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.07416055630892515
  lightness: 0.310828470159322
  saturation: 0.13265938078984618
  rhythmicContrast: 0.6686245007440448
purpose: []
